### ISSUE TITLE
Add new AI models

### ISSUE THREAD

**Issue by Tarek-Hasan** [UserUnknownFactor/GIMP-ML#2]
Please add these powerful general uses AI models
- [LaMa](https://github.com/saic-mdal/lama):
   Resolution-robust Large Mask Inpainting with Fourier Convolutions, WACV 2022 by Samsung Research. Alternatively, for automatic image inpainting [LaMa with MaskDINO](https://github.com/qwopqwop200/lama-with-maskdino).
- [DeOldify](https://github.com/jantic/DeOldify):
   A Deep Learning based project for colorizing and restoring old images.
- [DIS](https://github.com/xuebinqin/DIS) (v2 upcoming):
   Highly Accurate Dichotomous Image Segmentation from the maker of [U2-Net](https://github.com/xuebinqin/U-2-Net).

**Comment by UserUnknownFactor** [comment]
Those are very nice models and definitely deserve to be added, but I can only work with low-memory models that my potato-specs notebook can handle. Also DIS is kinda difficult to add due to how it's made...
